// <auto-generated />
using System;
using Fretefy.Test.Infra.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fretefy.Test.Infra.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    partial class BaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<Guid>("EstadoId")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("ESTADO_ID");

                    b.Property<Guid?>("EstadoId1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("EstadoId1");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("CIDADE");
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("SIGLA");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("ESTADO");
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Regiao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<int>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ATIVO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("REGIAO");
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.RelacionamentoRegiaoCidadeUF", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<Guid?>("CidadeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("CIDADE_ID");

                    b.Property<Guid?>("EstadoId")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("ESTADO_ID");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("REGIAO_ID");

                    b.Property<Guid?>("RegiaoId1")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("RegiaoId1");

                    b.HasIndex("RegiaoId", "CidadeId")
                        .IsUnique()
                        .HasFilter("\"CIDADE_ID\" IS NOT NULL");

                    b.HasIndex("RegiaoId", "EstadoId")
                        .IsUnique()
                        .HasFilter("\"ESTADO_ID\" IS NOT NULL");

                    b.ToTable("REL_REGIAO_CIDADE");
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Cidade", b =>
                {
                    b.HasOne("Fretefy.Test.Domain.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fretefy.Test.Domain.Entities.Estado", null)
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId1");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.RelacionamentoRegiaoCidadeUF", b =>
                {
                    b.HasOne("Fretefy.Test.Domain.Entities.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId");

                    b.HasOne("Fretefy.Test.Domain.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId");

                    b.HasOne("Fretefy.Test.Domain.Entities.Regiao", "Regiao")
                        .WithMany()
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fretefy.Test.Domain.Entities.Regiao", null)
                        .WithMany("RelacionamentosRegiaoCidadesUF")
                        .HasForeignKey("RegiaoId1");

                    b.Navigation("Cidade");

                    b.Navigation("Estado");

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Regiao", b =>
                {
                    b.Navigation("RelacionamentosRegiaoCidadesUF");
                });
#pragma warning restore 612, 618
        }
    }
}
