//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fretefy.Test.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensRegiaoServiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensRegiaoServiceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fretefy.Test.Domain.Resources.MensagensRegiaoServiceResource", typeof(MensagensRegiaoServiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cidade {0} foi informada mais de uma vez..
        /// </summary>
        public static string RegiaoServiceCidadeDuplicada {
            get {
                return ResourceManager.GetString("RegiaoServiceCidadeDuplicada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cidade com ID {0} não existe..
        /// </summary>
        public static string RegiaoServiceCidadeNaoEncontrada {
            get {
                return ResourceManager.GetString("RegiaoServiceCidadeNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estado {0} foi informado mais de uma vez..
        /// </summary>
        public static string RegiaoServiceEstadoDuplicado {
            get {
                return ResourceManager.GetString("RegiaoServiceEstadoDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estado com ID {0} não existe..
        /// </summary>
        public static string RegiaoServiceEstadoNaoEncontado {
            get {
                return ResourceManager.GetString("RegiaoServiceEstadoNaoEncontado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Região não encontrada..
        /// </summary>
        public static string RegiaoServiceRegiaoNaoEncontrada {
            get {
                return ResourceManager.GetString("RegiaoServiceRegiaoNaoEncontrada", resourceCulture);
            }
        }
    }
}
